name: ci

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  gitleaks:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install just and gitleaks
        run: sudo apt-get update && sudo apt-get install -y just gitleaks
      - name: Scan for secrets
        run: just gitleaks

  shellcheck:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install just and shellcheck
        run: sudo apt-get update && sudo apt-get install -y just shellcheck
      - name: Run shellcheck
        run: just shellcheck

  shfmt:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install just and shfmt
        run: sudo apt-get update && sudo apt-get install -y just shfmt
      - name: Run shfmt
        run: just shfmt
